### ISSUE TITLE
Login fails with Error: UreqErr onprivate vaultwarden instance with 2FA

### ISSUE THREAD

**Issue by qdlmcfresh** [haipengno1/bw-key#1]
Hi, i tried running this with a private vaultwarden instance and yubikey 2FA but after entering my password i get `Error: UreqErr` so i guess the login is not working.

**Comment by haipengno1** [comment]
Not currently supported, I'll add it soon

**Comment by haipengno1** [comment]
Can you test the 0.0.2 version? I don't have a yubikey

**Comment by qdlmcfresh** [comment]
Sure give me a minute

**Comment by qdlmcfresh** [comment]
On my vaultwarden instance(yubikey):
```
Please input your password:
Please input  two factor code:***************
Error: UreqErr
```
Just tried with an OTP app on my phone and that gives me `Error: UreqErr` aswell.
Also created an account with bitwarden.com and enabled OTP(auth) there:
```
Please input your password:
Please input  two factor code:******
Error: Ureq { source: Custom { kind: InvalidData, error: "Failed to read JSON: missing field `Kdf` at line 1 column 30" } }
```

**Comment by qdlmcfresh** [comment]
With vaultwarden it fails at the prelogin stage with:
```rust
Err(Transport(Transport { kind: InvalidUrl, message: Some("failed to parse URL: RelativeUrlWithoutBase"), url: None, source: Some(RelativeUrlWithoutBase) }))
```

**Comment by haipengno1** [comment]
Maybe I need to buy a yubikey for test, before that, you can use "Google Authenticator" instead

**Comment by qdlmcfresh** [comment]
As i said above it doesnt work with an authenticator app aswell ... 

> Just tried with an OTP app on my phone and that gives me `Error: UreqErr` aswell. Also created an account with bitwarden.com and enabled OTP(auth) there:
> 
> ```
> Please input your password:
> Please input  two factor code:******
> Error: Ureq { source: Custom { kind: InvalidData, error: "Failed to read JSON: missing field `Kdf` at line 1 column 30" } }
> ```

And since it fails at prelogin already the authentication method shouldnt even matter at this point

**Comment by haipengno1** [comment]
I tested it with "Google Authenticator" App on my Mac, Vaultwarden instance version is vaultwarden/server:1.24.0
```
./bw-key -h http://127.0.0.1:8843 -n xxxxx@gmail.com -m auth
Please input your password:
Please input  two factor code:******
 Found SSH folder.
```
Which OS are you using？

**Comment by qdlmcfresh** [comment]
Im using this https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose on an ubuntu server

**Comment by haipengno1** [comment]
Which OS is bw-key running on?

**Comment by qdlmcfresh** [comment]
windows

**Comment by qdlmcfresh** [comment]
But i noticed the request fails also in the browser...
![grafik](https://user-images.githubusercontent.com/10837173/154519013-f67240fa-2303-4780-8354-87ec3de0d2f9.png)
with api.bitwarden.com it works though
![grafik](https://user-images.githubusercontent.com/10837173/154519217-c4c56233-f5d4-415d-a6c1-1bb0cb68d67d.png)

but i still get an error with bitwarden.com
```
     Running `target\debug\bw-key.exe --name mymail@gmail.com --method auth`
Please input your password:
Please input  two factor code:123456
Ok(Response[status: 200, status_text: OK, url: https://api.bitwarden.com/accounts/prelogin])
Error: Ureq { source: Custom { kind: InvalidData, error: "Failed to read JSON: missing field `Kdf` at line 1 column 30" } }
error: process didn't exit successfully: `target\debug\bw-key.exe --name mymail@gmail.com --method auth` (exit code: 1)
```

**Comment by haipengno1** [comment]
The correct address of the prelogin of the self-hosted instance is http://xxxxx.com/api/accounts/prelogin
You missed '/api'

**Comment by qdlmcfresh** [comment]
Using `--host https://domain.de` instead of  `--host domain.de ` let me log in. Yubikey works aswell. Thanks for your work :)

**Comment by haipengno1** [comment]
You're welcome
