### ISSUE TITLE
libssl3 dependency not met, ubuntu focal

### ISSUE THREAD

**Issue by dkebler** [haipengno1/bw-key#2]
```
bw-key
bw-key: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

what version of openssl is required?  I'm running focal (20.04) which has openssl1.1.1  as the latest?
https://github.com/openssl/openssl/tags

Did you compile this for openssl3?  If so not sure if I can upgrade on 20.04 without breaking my install. Possible to compile for 1.1.1?

Do have a DOCKERFILE I can run instead that uses cargo.

**Comment by haipengno1** [comment]
I use git-actions to build the version, which runs on ubuntu-latest , probably 22.04.
Please check the .github/workflows/release.yml file in the project.
If it doesn't work on your system, you can compile it yourself.

**Comment by haipengno1** [comment]
I use git-actions to build the version, which runs on ubuntu-latest , probably 22.04.
Please check the .github/workflows/release.yml file in the project.
If it doesn't work on your system, you can compile it yourself.

**Comment by haipengno1** [comment]
Can you test the 0.1.1 version?

**Comment by haipengno1** [comment]
No information updated for too long, close the issue. If any problem, please reopenit.
