### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by dkebler** [haipengno1/bw-key#3]
Started this in a multipass ubuntu 22.04 jammy instance.
I have a ssh-agent runnig 
I have a key in SSH folder.  It is found but then this error.  Looks like something to do with connecting to ssh agent socket

```
RUST_BACKTRACE=full /opt/bin/bw-key -h https://pw.kebler.net -n dgkebler+test@gmail.com
Please input your password: 
 Found SSH folder.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/sshsock.rs:22:67
stack backtrace:
   0:     0x5618d3d1e970 - <unknown>
   1:     0x5618d3c8720e - <unknown>
   2:     0x5618d3cf97d4 - <unknown>
   3:     0x5618d3d1f8e3 - <unknown>
   4:     0x5618d3d2080d - <unknown>
   5:     0x5618d3d203d2 - <unknown>
   6:     0x5618d3d2033c - <unknown>
   7:     0x5618d3d20311 - <unknown>
   8:     0x5618d3bf1302 - <unknown>
   9:     0x5618d3bf1582 - <unknown>
  10:     0x5618d3c44655 - <unknown>
  11:     0x5618d3c3e3ac - <unknown>
  12:     0x5618d3c43aa3 - <unknown>
  13:     0x5618d3c3835c - <unknown>
  14:     0x7fd31798ad90 - <unknown>
  15:     0x7fd31798ae40 - __libc_start_main
  16:     0x5618d3bf5a65 - <unknown>
  17:                0x0 - <unknown>

service running
```
[Unit]
Description=SSH key agent
Wants=environment.target
Before=environment.target
IgnoreOnIsolate=true
 
[Service]
Type=forking
Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
ExecStart=/usr/bin/ssh-agent -a $SSH_AUTH_SOCK -t 1800
ExecStartPost=/bin/sh -c "/bin/ps --no-headers -o pid -C ssh-agent | sed 's/^ /export SSH_AGENT_PID=/' > ~/ssh-agent.properties"
ExecStartPost=/bin/sh -c "echo export SSH_AUTH_SOCK=$SSH_AUTH_SOCK >> ~/ssh-agent.properties"
ExecStartPost=/bin/systemctl --user set-environment SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
ExecStartPost=/bin/sh -c "echo in custom agent service"
#ExecStop=/usr/bin/ssh-agent -k
ExecStopPost=/bin/rm ${SSH_AUTH_SOCK}
 
[Install]
WantedBy=default.target
```
service status
```
ubuntu@temp:~$ systemctl --user status ssh-agentc
● ssh-agentc.service - SSH key agent
     Loaded: loaded (/home/ubuntu/.config/systemd/user/ssh-agentc.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-12-06 13:25:32 PST; 2min 35s ago
    Process: 4418 ExecStart=/usr/bin/ssh-agent -a $SSH_AUTH_SOCK -t 1800 (code=exited, status=0/SUCCESS)
    Process: 4420 ExecStartPost=/bin/sh -c /bin/ps --no-headers -o pid -C ssh-agent | sed 's/^ /export SSH_AGENT_PID=/' > ~/ssh-agent.properties (code=exited, status=0/SUCC>
    Process: 4423 ExecStartPost=/bin/sh -c echo export SSH_AUTH_SOCK=$SSH_AUTH_SOCK >> ~/ssh-agent.properties (code=exited, status=0/SUCCESS)
    Process: 4424 ExecStartPost=/bin/systemctl --user set-environment SSH_AUTH_SOCK=${SSH_AUTH_SOCK} (code=exited, status=0/SUCCESS)
    Process: 4425 ExecStartPost=/bin/sh -c echo in custom agent service (code=exited, status=0/SUCCESS)
   Main PID: 4419 (ssh-agent)
      Tasks: 1 (limit: 1116)
     Memory: 1.5M
        CPU: 29ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/ssh-agentc.service
             └─4419 /usr/bin/ssh-agent -a /run/user/1000/ssh-agent.socket -t 1800

Dec 06 13:25:32 temp systemd[1664]: Starting SSH key agent...
Dec 06 13:25:32 temp ssh-agent[4418]: SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket; export SSH_AUTH_SOCK;
Dec 06 13:25:32 temp ssh-agent[4418]: SSH_AGENT_PID=4419; export SSH_AGENT_PID;
Dec 06 13:25:32 temp ssh-agent[4418]: echo Agent pid 4419;
Dec 06 13:25:32 temp sh[4425]: in custom agent service
Dec 06 13:25:32 temp systemd[1664]: Started SSH key agent.
lines 1-21/21 (END)
```

**Comment by haipengno1** [comment]
Do you running the ssh-agent service on the host and the bw-key program on the multipass  instance?
You need to map the sh agent socket path to the instance.

**Comment by haipengno1** [comment]
No information updated for too long, close the issue. If any problem, please reopenit.
